build:
  environment:
    apt_packages:
      - texlive
      - latexmk
    variables:
      XDEBUG_MODE: coverage
    php:
      version: 8.1
  dependencies:
    override:
      - composer install --no-interaction --prefer-dist --no-plugins
  nodes:
    coverage:
      tests:
        override:
          - command: ./vendor/bin/phpunit
            coverage:
              file: clover.xml
              format: clover
