build:
  environment:
    php:
      version: 8.1
  dependencies:
    override:
      - composer install --no-interaction --prefer-dist --no-plugins
  nodes:
    coverage:
      tests:
        override:
          - command: composer test
            coverage:
              file: clover.xml
              format: clover
