name: 'Netlify Deploy'

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up TeXLive
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: scheme-basic latexmk listings float

      - name: Build
        run: |
          composer install
          ./bin/basildon build docs

      - name: Deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install netlify-cli -g
          netlify deploy --prod --dir=docs/output/
