name: Psalm Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '33 22 * * 5'

permissions:
  contents: read

jobs:
  psalm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Psalm Security Scan
        uses: docker://ghcr.io/psalm/psalm-github-actions
        with:
            security_analysis: true
